# Generated by Django 4.2.16 on 2025-10-13 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(help_text='Push service endpoint URL', max_length=500, unique=True)),
                ('p256dh', models.CharField(help_text='Client public key for encryption', max_length=255)),
                ('auth', models.CharField(help_text='Client authentication secret', max_length=255)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device user agent string')),
                ('device_name', models.CharField(blank=True, help_text='Optional device identifier', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subscription is active')),
                ('user', models.ForeignKey(help_text='User who owns this subscription', on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Subscription',
                'verbose_name_plural': 'Push Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('alert', 'Device Alert'), ('warning', 'Warning'), ('critical', 'Critical'), ('info', 'Information'), ('success', 'Success')], default='info', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('expired', 'Expired Subscription')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if sending failed')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data (device_id, alert_id, etc.)')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='notifications.pushsubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['user'], name='idx_push_user'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['is_active'], name='idx_push_active'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['created_at'], name='idx_push_created'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', '-sent_at'], name='idx_notif_user_sent'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='idx_notif_status'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification_type'], name='idx_notif_type'),
        ),
    ]
