# Generated by Django 4.2.16 on 2025-10-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreferences',
            name='email_enabled',
            field=models.BooleanField(default=False, help_text='Receive alerts via email'),
        ),
    ]
