# Generated by Django 4.2.16 on 2025-10-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationpreferences_email_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreferences',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=False, help_text='Enable quiet hours to silence non-critical notifications'),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='quiet_hours_end',
            field=models.TimeField(default='07:00', help_text='End time for quiet hours (24-hour format)'),
        ),
        migrations.AddField(
            model_name='notificationpreferences',
            name='quiet_hours_start',
            field=models.TimeField(default='22:00', help_text='Start time for quiet hours (24-hour format)'),
        ),
    ]
