# Generated by ChatGPT on 2025-11-18
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0014_remove_alert_reservoir'),
        ('notifications', '0005_notificationlog_read_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAlertReadReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_read_receipts', to='sensors.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_alert_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Alert Read Receipt',
                'verbose_name_plural': 'Admin Alert Read Receipts',
            },
        ),
        migrations.AddIndex(
            model_name='adminalertreadreceipt',
            index=models.Index(fields=['user'], name='idx_adminread_user'),
        ),
        migrations.AddIndex(
            model_name='adminalertreadreceipt',
            index=models.Index(fields=['alert'], name='idx_adminread_alert'),
        ),
        migrations.AddIndex(
            model_name='adminalertreadreceipt',
            index=models.Index(fields=['read_at'], name='idx_adminread_read_at'),
        ),
        migrations.AlterUniqueTogether(
            name='adminalertreadreceipt',
            unique_together={('user', 'alert')},
        ),
    ]
