# Generated by Django 5.2.8 on 2025-11-19 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_adminalertreadreceipt_id'),
        ('sensors', '0015_add_alert_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminalertreadreceipt',
            name='alert',
            field=models.ForeignKey(help_text='Sensor alert that was read by the admin', on_delete=django.db.models.deletion.CASCADE, related_name='admin_read_receipts', to='sensors.alert'),
        ),
        migrations.AlterField(
            model_name='adminalertreadreceipt',
            name='user',
            field=models.ForeignKey(help_text='Admin user who read this alert in the admin UI', on_delete=django.db.models.deletion.CASCADE, related_name='admin_alert_reads', to=settings.AUTH_USER_MODEL),
        ),
    ]
