# Generated by Django 4.2 on 2025-09-16 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('decommissioned', 'Decommissioned')], db_index=True, default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('ph', 'pH'), ('ec', 'Electrical Conductivity'), ('light', 'Light'), ('other', 'Other')], db_index=True, max_length=30)),
                ('unit', models.CharField(max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='monitoring.device')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitoring.sensor')),
            ],
            options={
                'verbose_name': 'Sensor Data',
                'verbose_name_plural': 'Sensor Data',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservoir_name', models.CharField(max_length=100)),
                ('plant_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservoirs', to='monitoring.device')),
            ],
            options={
                'verbose_name': 'Reservoir',
                'verbose_name_plural': 'Reservoirs',
            },
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['sensor', 'created_at'], name='idx_sensordata_sensor_created'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['device', 'sensor_type'], name='idx_sensor_device_type'),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(fields=('device', 'sensor_type', 'unit'), name='uq_sensor_device_type_unit'),
        ),
        migrations.AddIndex(
            model_name='reservoir',
            index=models.Index(fields=['device', 'start_date'], name='idx_reservoir_device_start'),
        ),
        migrations.AddConstraint(
            model_name='reservoir',
            constraint=models.UniqueConstraint(fields=('device', 'reservoir_name'), name='uq_reservoir_device_name'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'status'], name='idx_device_user_status'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('user', 'device_name'), name='uq_device_user_name'),
        ),
    ]
