# Generated by Django 4.2 on 2025-09-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_specify_other_and_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('temperature', 'Temperature'), ('water_temperature', 'Water Temperature'), ('air_temperature', 'Air Temperature'), ('humidity', 'Humidity'), ('ph', 'pH'), ('ec', 'Electrical Conductivity'), ('light', 'Light'), ('co2', 'CO₂'), ('water_level', 'Water Level'), ('turbidity', 'Turbidity'), ('other', 'Other')], db_index=True, max_length=30),
        ),
    ]
