# Generated by Django 4.2.16 on 2025-10-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_sensor_sensor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('temperature', 'Temperature'), ('water_temperature', 'Water Temperature'), ('air_temperature', 'Air Temperature'), ('humidity', 'Humidity'), ('ph', 'pH'), ('tds', 'Total Dissolved Solids (PPM)'), ('light', 'Light'), ('co2', 'CO₂'), ('water_level', 'Water Level'), ('turbidity', 'Turbidity'), ('other', 'Other')], db_index=True, max_length=30),
        ),
    ]
