# Generated by Django 5.1.6 on 2025-05-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydroponics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WaterLogs',
            new_name='WaterLog',
        ),
    ]
