# Generated by Django 5.1.6 on 2025-05-13 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydroponics', '0002_rename_waterlogs_waterlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hydroponic',
            options={'verbose_name': 'Hydroponic System', 'verbose_name_plural': 'Hydroponic Systems'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensors'},
        ),
        migrations.AlterModelOptions(
            name='smartanom',
            options={'verbose_name': 'SmarTanom', 'verbose_name_plural': 'SmarTanom'},
        ),
        migrations.AlterModelOptions(
            name='smartanomdata',
            options={'verbose_name': 'SmarTanom Data', 'verbose_name_plural': 'SmarTanom Data'},
        ),
        migrations.AlterModelOptions(
            name='waterlog',
            options={'verbose_name': 'Water Log', 'verbose_name_plural': 'Water Logs'},
        ),
    ]
