# Generated by Django 5.1.6 on 2025-05-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydroponics', '0003_alter_hydroponic_options_alter_sensor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartanomdata',
            name='data_type',
            field=models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
