# Generated by Django 4.2.16 on 2025-10-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservoir_name', models.CharField(max_length=100)),
                ('plant_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservoirs', to='devices.device')),
            ],
            options={
                'verbose_name': 'Reservoir',
                'verbose_name_plural': 'Reservoirs',
                'indexes': [models.Index(fields=['device', 'start_date'], name='idx_newreservoir_device_start')],
            },
        ),
        migrations.AddConstraint(
            model_name='reservoir',
            constraint=models.UniqueConstraint(fields=('device', 'reservoir_name'), name='uq_newreservoir_device_name'),
        ),
    ]
