# Generated by ChatGPT on 2025-11-14
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservoirs", "0005_plant_ec_max_plant_ec_min"),
        ("devices", "0015_copy_reservoir_to_device"),
        ("sensors", "0014_remove_alert_reservoir"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Reservoir",
        ),
    ]
