# Generated by Django 4.2.16 on 2025-10-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username_user_auth_user_usernam_f2740e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
