# Generated by Django 4.2.16 on 2025-10-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'Registration'), ('reset', 'Password Reset'), ('revoke', 'Device Access Revocation')], default='login', max_length=20),
        ),
    ]
