# Generated by Django 4.2.16 on 2025-10-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
