# Generated by Django 4.2.16 on 2025-10-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_push_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('register', 'Registration'), ('reset', 'Password Reset'), ('revoke', 'Device Access Revocation'), ('remove_ownership', 'Device Ownership Removal')], default='login', max_length=20),
        ),
    ]
