# Generated by Django 4.2.16 on 2025-10-10 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Owner of the device. Null for unowned devices.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
