# Generated by Django 4.2.16 on 2025-10-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_serial',
            field=models.CharField(blank=True, help_text='Unique device serial number (SMRT-XXX-XXX format)', max_length=12, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_serial'], name='idx_device_serial'),
        ),
    ]
