# Generated by Django 4.2.16 on 2025-10-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_device_serial_device_idx_device_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_serial',
            field=models.CharField(default=1, help_text='Unique device serial number (SMRT-XXX-XXX format)', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
