# Generated by Django 4.2.16 on 2025-10-10 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_device_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='bound_email',
            field=models.EmailField(blank=True, help_text='Email address this device is bound to', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='is_bound',
            field=models.BooleanField(default=False, help_text='Whether this device has been bound to an email address'),
        ),
        migrations.CreateModel(
            name='DeviceOTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='devices.device')),
            ],
            options={
                'verbose_name': 'Device OTP Code',
                'verbose_name_plural': 'Device OTP Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'email', 'is_verified'], name='devices_dev_device__edc46b_idx'), models.Index(fields=['expires_at'], name='devices_dev_expires_dc408a_idx')],
            },
        ),
    ]
