# Generated by Django 4.2.16 on 2025-10-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_bound_email_device_is_bound_deviceotpcode'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='device',
            name='uq_newdevice_user_name',
        ),
        migrations.RemoveIndex(
            model_name='device',
            name='idx_newdevice_user_status',
        ),
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='idx_device_status'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_bound'], name='idx_device_is_bound'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['bound_email'], name='idx_device_bound_email'),
        ),
    ]
