# Generated by Django 4.2.16 on 2025-10-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_remove_user_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='plant_name',
            field=models.CharField(blank=True, help_text='Name of the plant being grown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='plant_photo',
            field=models.ImageField(blank=True, help_text='Photo of the plant growing in this device', null=True, upload_to='device_photos/'),
        ),
        migrations.AddField(
            model_name='device',
            name='plant_status',
            field=models.CharField(blank=True, default='Active', help_text='Current status of the plant', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='plant_variety',
            field=models.CharField(blank=True, help_text='Specific variety of the plant', max_length=100, null=True),
        ),
    ]
