# Generated by Django 4.2.16 on 2025-10-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_add_plant_photo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, help_text='Optional location or placement description for the device', max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['location'], name='idx_device_location'),
        ),
    ]
