# Generated by Django 4.2 on 2025-10-12
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_device_location_device_idx_device_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='plant_name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='plant_variety',
        ),
        migrations.RemoveField(
            model_name='device',
            name='plant_status',
        ),
    ]
