# Generated by Django 4.2.16 on 2025-10-12 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_remove_plant_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborator_email', models.EmailField(help_text='Email address of the collaborator', max_length=254)),
                ('permissions', models.CharField(choices=[('view_only', 'View Only'), ('manage', 'Manage')], default='view_only', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('shared_by_email', models.EmailField(help_text='Email address of the user who shared this device', max_length=254)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='devices.device')),
            ],
            options={
                'verbose_name': 'Device Collaboration',
                'verbose_name_plural': 'Device Collaborations',
            },
        ),
        migrations.CreateModel(
            name='DeviceInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invite_email', models.EmailField(help_text='Email address being invited', max_length=254)),
                ('invited_by_email', models.EmailField(help_text='Email address of the user sending the invitation', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message from the inviter')),
                ('permissions', models.CharField(choices=[('view_only', 'View Only'), ('manage', 'Manage')], default='view_only', max_length=20)),
                ('token', models.CharField(help_text='Unique token for accepting/declining invitation', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='devices.device')),
            ],
            options={
                'verbose_name': 'Device Invitation',
                'verbose_name_plural': 'Device Invitations',
                'indexes': [models.Index(fields=['device'], name='idx_invitation_device'), models.Index(fields=['invite_email'], name='idx_invitation_email'), models.Index(fields=['invited_by_email'], name='idx_invitation_invited_by'), models.Index(fields=['status'], name='idx_invitation_status'), models.Index(fields=['token'], name='idx_invitation_token'), models.Index(fields=['expires_at'], name='idx_invitation_expires')],
            },
        ),
        migrations.AddConstraint(
            model_name='deviceinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('device', 'invite_email'), name='unique_device_invitation'),
        ),
        migrations.AddIndex(
            model_name='devicecollaboration',
            index=models.Index(fields=['device'], name='idx_collaboration_device'),
        ),
        migrations.AddIndex(
            model_name='devicecollaboration',
            index=models.Index(fields=['collaborator_email'], name='idx_collaboration_collaborator'),
        ),
        migrations.AddIndex(
            model_name='devicecollaboration',
            index=models.Index(fields=['shared_by_email'], name='idx_collaboration_shared_by'),
        ),
        migrations.AddIndex(
            model_name='devicecollaboration',
            index=models.Index(fields=['status'], name='idx_collaboration_status'),
        ),
        migrations.AddConstraint(
            model_name='devicecollaboration',
            constraint=models.UniqueConstraint(fields=('device', 'collaborator_email'), name='unique_device_collaborator'),
        ),
    ]
