# Generated by Django 4.2.16 on 2025-10-14 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0010_add_device_collaboration_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecollaboration',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who added this collaborator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborations_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicecollaboration',
            name='revoked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when collaboration was revoked', null=True),
        ),
        migrations.AddField(
            model_name='devicecollaboration',
            name='revoked_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who revoked this collaboration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborations_revoked', to=settings.AUTH_USER_MODEL),
        ),
    ]
