# Generated by ChatGPT on 2025-11-14
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservoirs", "0005_plant_ec_max_plant_ec_min"),
        ("devices", "0013_device_ip_address_device_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="plant",
            field=models.ForeignKey(
                related_name="devices",
                on_delete=django.db.models.deletion.PROTECT,
                to="reservoirs.plant",
                null=True,
                blank=True,
                help_text="Selected plant/crop grown on this device",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="start_date",
            field=models.DateField(null=True, blank=True, help_text="Cycle start date"),
        ),
        migrations.AddField(
            model_name="device",
            name="end_date",
            field=models.DateField(null=True, blank=True, help_text="Cycle end date"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["plant"], name="idx_device_plant"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["start_date"], name="idx_device_start_date"),
        ),
    ]
