# Generated by ChatGPT on 2025-11-14
from django.db import migrations


def copy_reservoir_data(apps, schema_editor):
    Device = apps.get_model("devices", "Device")
    Reservoir = None
    try:
        Reservoir = apps.get_model("reservoirs", "Reservoir")
    except LookupError:
        Reservoir = None

    if Reservoir is None:
        return

    # Iterate devices; for each, pick the latest reservoir by created_at if exists
    for device in Device.objects.all().iterator():
        try:
            r = Reservoir.objects.filter(device_id=device.id).order_by("-created_at").first()
            if not r:
                continue
            # Assign fields
            device.plant_id = r.plant_id
            device.start_date = r.start_date
            device.end_date = r.end_date
            device.save(update_fields=["plant", "start_date", "end_date"])
        except Exception:
            # Skip on error to avoid migration failure for a single row
            continue


def noop_reverse(apps, schema_editor):
    # No-op reverse migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0014_device_plant_cycle_fields"),
        ("reservoirs", "0005_plant_ec_max_plant_ec_min"),
    ]

    operations = [
        migrations.RunPython(copy_reservoir_data, reverse_code=noop_reverse),
    ]
