# Generated by Django 4.2.16 on 2025-10-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor_type', models.CharField(choices=[('water_temperature', 'Water Temperature (°C)'), ('air_temperature', 'Air Temperature (°C)'), ('humidity', 'Humidity (%)'), ('ph', 'pH'), ('tds', 'Total Dissolved Solids (ppm)'), ('light', 'Light (lux)'), ('water_level', 'Water Level'), ('turbidity', 'Turbidity (NTU)'), ('other', 'Other')], db_index=True, max_length=30)),
                ('unit', models.CharField(max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='devices.device')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
            options={
                'verbose_name': 'Sensor Data',
                'verbose_name_plural': 'Sensor Data',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['sensor', 'created_at'], name='idx_newsens_data_created')],
            },
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['device', 'sensor_type'], name='idx_newsensor_device_type'),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(fields=('device', 'sensor_type', 'unit'), name='uq_newsensor_device_type_unit'),
        ),
    ]
