# Generated by Django 4.2.16 on 2025-10-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('water_temperature', 'Water Temperature (°C)'), ('humidity', 'Humidity (%)'), ('ph', 'pH'), ('tds', 'Total Dissolved Solids (ppm)'), ('light', 'Light (lux)'), ('water_level', 'Water Level'), ('turbidity', 'Turbidity (NTU)'), ('other', 'Other')], db_index=True, max_length=30),
        ),
    ]
