# Generated by Django 4.2.16 on 2025-10-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_remove_air_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('ph', 'pH Sensor'), ('tds', 'TDS Sensor (ppm)'), ('water_temperature', 'Water Temperature Sensor (°C)'), ('water_level', 'Water Level Sensor'), ('air_temperature', 'Air Temperature - DHT22 (°C)'), ('humidity', 'Humidity - DHT22 (%)'), ('light', 'Light Sensor - BH1750 (lux)')], db_index=True, max_length=30),
        ),
    ]
