# Generated by Django 4.2.16 on 2025-10-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_alter_sensor_sensor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('ph', 'pH Sensor'), ('tds', 'TDS Sensor (ppm)'), ('ec', 'Electrical Conductivity (mS/cm)'), ('water_temperature', 'Water Temperature Sensor (°C)'), ('water_level', 'Water Level Sensor'), ('turbidity', 'Turbidity Sensor (NTU)'), ('air_temperature', 'Air Temperature - DHT22 (°C)'), ('humidity', 'Humidity - DHT22 (%)'), ('light', 'Light Sensor - BH1750 (lux)')], db_index=True, max_length=30),
        ),
    ]
