# Generated by Django 4.2.16 on 2025-10-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_alter_sensor_sensor_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sensordata',
            new_name='idx_sens_data_created',
            old_name='idx_newsens_data_created',
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['created_at'], name='idx_sens_data_created_at'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['sensor', 'value'], name='idx_sens_data_value'),
        ),
    ]
