# Generated by Django 4.2.16 on 2025-10-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0009_prune_env_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='plant_category',
            field=models.CharField(choices=[('Lettuce', 'Lettuce'), ('Lettuce_Germination', 'Lettuce - Germination'), ('Lettuce_Seedling', 'Lettuce - Seedling'), ('Basil', 'Basil'), ('Basil_Germination', 'Basil - Germination'), ('Basil_Seedling', 'Basil - Seedling'), ('Pechay', 'Pechay'), ('Pechay_Germination', 'Pechay - Germination'), ('Pechay_Seedling', 'Pechay - Seedling'), ('Generic', 'Generic')], db_index=True, default='Generic', max_length=32),
        ),
    ]
