# Generated by Django 4.2.16 on 2025-11-03 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0010_alter_alert_plant_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorLatest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latest', to='sensors.sensor')),
            ],
            options={
                'verbose_name': 'Sensor Latest',
                'verbose_name_plural': 'Sensors Latest',
                'db_table': 'sensor_latest',
                'indexes': [models.Index(fields=['updated_at'], name='idx_sensorlatest_updated')],
            },
        ),
    ]
