# Generated by Django 4.2.16 on 2025-11-09
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0002_add_ingest_id"),
        ("sensors", "0011_sensorlatest"),
    ]

    operations = [
        # No-op merge migration to resolve divergent histories
    ]
