# Generated by Django 4.2.16 on 2025-11-09
from django.db import migrations, models
import django.db.models


def forwards(apps, schema_editor):
    SensorData = apps.get_model('sensors', 'SensorData')
    # Best-effort cleanup: convert empty-string ingest_id to NULL to reduce noise
    try:
        SensorData.objects.filter(ingest_id="").update(ingest_id=None)
    except Exception:
        pass


def backwards(apps, schema_editor):
    # No-op: we won't convert NULL back to empty strings
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0012_merge_0002_0011"),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='ingest_id',
            field=models.CharField(max_length=64, blank=True, null=True, default=None, db_index=True),
        ),
        # Replace any previous unconditional unique constraint with conditional one
        migrations.RemoveConstraint(
            model_name='sensordata',
            name='uniq_sensor_ingest_id',
        ),
        migrations.AddConstraint(
            model_name='sensordata',
            constraint=models.UniqueConstraint(
                fields=("sensor", "ingest_id"),
                name='uniq_sensor_ingest_id',
                condition=(~django.db.models.Q(ingest_id__isnull=True) & ~django.db.models.Q(ingest_id="")),
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
