# Generated by ChatGPT on 2025-11-14
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0013_adjust_ingest_id_constraint"),
        ("reservoirs", "0005_plant_ec_max_plant_ec_min"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="reservoir",
        ),
    ]
