# Generated by GitHub Copilot
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0014_remove_alert_reservoir"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="is_read",
            field=models.BooleanField(default=False, db_index=True),
        ),
    ]
